### PR TITLE
Make bundler available, automatically activate gems, remove bundler_setup

### PR DESCRIPTION
**Pull request by ClareCat**
**Bundler install changes**
The way bundler was being installed meant it didn't have standard gem directories so it was never possible to require bundler inside a ruby script which was breaking some projects. Instead of directly downloading the bundler gem and manually unpacking it this changes just runs `gem install bundler`. It's both simpler and consistent with how most people install bundler so should be less likely to break.

**Gem activation changes**
We don't use bundler to start up the ruby binary so none of the gems are activated (they are loaded) which means Gems.loaded_specs is empty (aside: it really should be called Gem.activated_specs) and anything that uses Gems.loaded_specs is broken (ie ddtrace). I tried to have bundler available on startup which would cause the gems to be automatically activated, but it was causing a lot of other issues and I am out of time to work on this. Instead added a small script that activates each gem on startup. I have already checked and it only activates gems for the given rb_binary and not all gems that are installed into the workspace.

**Remove bundler_setup logic**
The bundler setup file is generated by the bundler standalone setting. It was dumping every single gem installed in the workspace into the load path of every single ruby binary and not providing much value. It's also unclear why it was added to the rubyopt of every gem when it was automatically added to deps.  I have left the standalone setting because it prevents bundler from modifying the environment (and depending on the Gemfile) which was causing bundler to attempt to load every gem in the workspace and, unsurprisingly, that won't work when every gem isn't available.

**Cleanup**
Deleted a bunch of unused/broken code because they weren't adding value, but were adding mental overhead.

### CODE REVIEW

**Review by mdehoog — DISMISSED** [review]

**Comment by heimdall-asguard** [comment]
Review Error for mdehoog @ 2020-06-22 23:58:23 UTC
User must have write permissions to review

**Review by volkangurel — APPROVED** [review]
Approving without completely groking the changes, so please take it with a grain of salt. The PR description makes sense, the changes match what I expect at a high level and are well tested.

**Comment by heimdall-asguard** [comment]
Review Error for volkangurel @ 2020-06-23 15:37:37 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by volkangurel — APPROVED** [review]

**Comment by heimdall-asguard** [comment]
Review Error for volkangurel @ 2020-06-23 15:38:01 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by volkangurel — DISMISSED** [review]

**Review by volkangurel — APPROVED** [review]

**Pull request merged**
